spring.application.name=blue_oasis
server.port=8002
# swagger-ui custom path
#springdoc.swagger-ui.path=/swagger-ui.html

#Data base configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/blue_oasis_stg
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# Security Config
# blueoasis
security.jwt.key.private=31c9c29caa7555ae309e959cb697c544b68388a252cdc5c69a3462a50420a894
security.jwt.user.generator=AUTH0JWT
